/*
 * EXTI_CFG.h
 *
 *  Created on: Aug 19, 2023
 *      Author: Shawky
 */

#ifndef EXTI_CFG_H_
#define EXTI_CFG_H_

#define GLOBAL_INTERRUPT			GLOBAL_INTERRUPT_ENABLE

#define EXTERNAL_INT0_TRIGGER		INT0_TRIGGER_RISING_EDGE

#define EXTERNAL_INT1_TRIGGER		INT1_TRIGGER_FALLING_EDGE

#define EXTERNAL_INT2_TRIGGER		INT2_TRIGGER_RISING_EDGE

#endif /* EXTI_CFG_H_ */
